//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialTradingPlatform.CrossCutting.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancialTradingPlatform.CrossCutting.Language.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should calculate correct number of SMA values.
        /// </summary>
        public static string CalculateCorrectSMA {
            get {
                return ResourceManager.GetString("CalculateCorrectSMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result should be an empty list for empty input data.
        /// </summary>
        public static string EmptyInputData {
            get {
                return ResourceManager.GetString("EmptyInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first SMA value is incorrect.
        /// </summary>
        public static string FirstSMAIncorrect {
            get {
                return ResourceManager.GetString("FirstSMAIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Histogram value is incorrect for the first result.
        /// </summary>
        public static string HistogramValueIncorrect {
            get {
                return ResourceManager.GetString("HistogramValueIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data for MACD calculation.
        /// </summary>
        public static string InsufficientData {
            get {
                return ResourceManager.GetString("InsufficientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MACD line value is incorrect for the first result.
        /// </summary>
        public static string MACDValueIncorrect {
            get {
                return ResourceManager.GetString("MACDValueIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result should not be null.
        /// </summary>
        public static string ResultShouldNotBeNull {
            get {
                return ResourceManager.GetString("ResultShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second SMA value is incorrec.
        /// </summary>
        public static string SecondSMAIncorrec {
            get {
                return ResourceManager.GetString("SecondSMAIncorrec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should calculate at least one MACD result.
        /// </summary>
        public static string ShouldCalculate {
            get {
                return ResourceManager.GetString("ShouldCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Signal line value is incorrect for the first result.
        /// </summary>
        public static string SignalValueIncorrect {
            get {
                return ResourceManager.GetString("SignalValueIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The third SMA value is incorrect.
        /// </summary>
        public static string ThirdSMAIncorrect {
            get {
                return ResourceManager.GetString("ThirdSMAIncorrect", resourceCulture);
            }
        }
    }
}
